  name: Solar System Workflow
  on:
    workflow_dispatch: null
    push:
      branches:
        - main
        - feature/*
  env:
    MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
    MONGO_USERNAME: superuser
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  jobs:
    unit-testing:
      name: Unit Testing
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup NodeJS Version
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Cache NPM dependencies
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: '${{ runner.os }}-node-modules-${{ hashFiles(''package-lock.json'') }}'    
        - name: Install Dependencies
          run: npm install
        - name: Unit Testing
          run: npm test
        - name: Archive Test Result
          if: always() 
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml
    code-coverage:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - continue-on-error: true
        run: npm run coverage
      - uses: actions/upload-artifact@v4
        with:
         name: Code-Coverage-Result
         path: coverage
         retention-days: 5         
    docker:
      runs-on: ubuntu-latest
      needs:
       - unit-testing
       - code-coverage
      steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert repository owner to lowercase
        id: lower
        run: |
          echo "repo=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
         context: .
         push: true
         tags: ghcr.io/${{ steps.lower.outputs.repo }}/solar-system:${{ github.sha }}  

    dev-deploy:
      name: Dev Deploy
      needs: docker
      runs-on: ubuntu-latest
      environment:
        name: development
      steps:
      - uses: helm/kind-action@v1
      - run: |
          sleep 60
          kubectl -n kube-system get pod
          set +e
          REPO_OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"
          kubectl run solar --image ghcr.io/${REPO_OWNER_LC}/solar-system:${{ github.sha }} \
            --env MONGO_URI=${{ env.MONGO_URI}} \
            --env MONGO_USERNAME=${{ env.MONGO_USERNAME}} \
            --env MONGO_PASSWORD=${{ env.MONGO_PASSWORD}}
          set -e
          echo "kubectl returned $?"
          kubectl -n default get pod
          sleep 10
